name: Github Pages

on:
  push:
    branches:
      - main # Here source code branch is `master`, it could be other branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # # Use GitHub Actions' cache to cache dependencies on servers
      # - name: Cache dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       .asdf/**
      #       vendor/bundle
      #     key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.key') }}
      #     restore-keys: |
      #       ${{ runner.os }}-cache-

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3" # Default is 3.2.0 version
          bundler: "2.4.20" # Default is compatible bundler version (~>2.5.0)

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site

      # Use GitHub Deploy Action to build and deploy to Github
      # For latest version: `jeffreytse/jekyll-deploy-action@master`
      - name: Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: "github" # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          # ssh_private_key: "" # It's your SSH private key (SSH approach)
          repository: "${{ github.repository }}" # Default is current repository
          branch: "gh-pages" # Default is gh-pages for github provider
          jekyll_src: "./" # Default is root directory
          jekyll_cfg: "_config.yml" # Default is _config.yml
          jekyll_baseurl: "" # Default is according to _config.yml
          cname: "" # Default is to not use a cname
          actor: "${{ github.actor }}" # Default is the GITHUB_ACTOR
          pre_build_commands: "" # Installing additional dependencies (Arch Linux)

      - name: Notify on failure
        if: failure()
        run: echo "Build or deploy failed. Please check the logs."
